FROM golang:1.22 as builder
# Define build env
ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64
# Add a work directory
RUN mkdir app
WORKDIR /app
# Cache and install dependencies

COPY go.mod go.sum ./
RUN go mod download
# Copy mmapp files
COPY . .

# CHANGE ME
RUN go build -o producer ./

FROM alpine:3.14 
# Add certificates
WORKDIR /producer
RUN apk add --no-cache ca-certificates
# Copy built binary from builder
COPY --from=builder /app .
# Expose port
EXPOSE 8080
# Exec built binary
# CHANGE ME
CMD ./producer 